---
sudo: required
language: python
services:
  - docker
cache:
  - pip
before_install:
  - sudo apt-get -qq update
install:
  - python --version
  - pip install -r install.txt
script:
  - molecule test
