---
# tasks file for common/macos
- name: Include macos vars
  include_vars:
    file: macos.yml

- name: Include geerlingguy.homebrew
  include_role:
    name: geerlingguy.homebrew

- name: Create home directories
  file:
    path: "{{ primary_homedir }}/{{ item }}"
    state: directory
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
    mode: 0755
  with_items:
    - bin
    - nginx
    - projects

- name: Include macos/python
  include_tasks: macos/python.yml
  tags: python

- name: Install simple programs
  homebrew:
    name: "{{ item.name }}"
    state: present
    install_options: "{{ item.options }}"
  with_items:
    - { name: "awscli", options: "" }
    - { name: "dnsmasq", options: "" }
    - { name: "htop", options: "" }
    - { name: "nginx", options: "" }
    - { name: "wget", options: "" }
    - { name: "make", options: "" }
    - { name: "redis", options: "" }
    - { name: "ruby", options: "" }
    - { name: "node", options: "" }
    - { name: "zsh", options: "" }
    - { name: "libtool", options: "universal" }
    - { name: "openssh", options: "with-brewed-openssl with-keychain-support" }
    - { name: "zsh", options: "" }

- name: Include macos/mysql
  include_tasks: macos/mysql.yml
  tags: mariadb mysql

- name: Include macos/php
  include_tasks: macos/php.yml
  tags: php

- name: Include macos/nginx
  include_tasks: macos/nginx.yml
  tags: nginx

- name: Include macos/mailcatcher
  include_tasks: macos/mailcatcher.yml
  tags: mailcatcher

- name: Include macos/dnsmasq
  include_tasks: macos/dnsmasq.yml
  tags: dnsmasq

- name: Include macos/npm.yml
  include_tasks: macos/npm.yml
  tags: npm

- name: Include common/zsh
  include_tasks: common/zsh.yml
  tags: zsh

- name: Init shell
  user:
    name: "{{ primary_user }}"
    shell: /bin/zsh
  tags: zsh
