---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: fedora32
    image: geerlingguy/docker-fedora32-ansible:latest
    command: /usr/lib/systemd/systemd
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
lint: |
  set -e
  yamllint defaults/ files/ handlers/ meta/ tasks/ templates/ vars/
  ansible-lint -x106,302,305,306 roles/ansible-workstation-common/
  flake8 molecule/default/tests/
scenario:
  name: default
