---
- name: Create php session directory
  file:
    path: "{{ php_session_directory }}"
    state: directory
    mode: 0755

- name: Install php 7.1
  homebrew:
    name: php@7.1
    state: present
  tags: php
- name: Install php71 ini configuration
  template:
    src: templates/php/99-local.ini.j2
    dest: /usr/local/etc/php/7.1/conf.d/99-local.ini
    mode: 0644
  notify: php71
  tags: php
- name: Install php71 fpm configuration
  vars:
    - php_fpm_port: 9071
  template:
    src: templates/php/www.local.conf.j2
    dest: /usr/local/etc/php/7.1/php-fpm.d/www.local.conf
    mode: 0644
  notify: php71
  tags: php

- name: Install php 7.2
  homebrew:
    name: php@7.2
    state: present
  tags: php
- name: Install php72 ini configuration
  template:
    src: templates/php/99-local.ini.j2
    dest: /usr/local/etc/php/7.2/conf.d/99-local.ini
    mode: 0644
  notify: php72
  tags: php
- name: Install php72 fpm configuration
  vars:
    - php_fpm_port: 9072
  template:
    src: templates/php/www.local.conf.j2
    dest: /usr/local/etc/php/7.2/php-fpm.d/www.local.conf
    mode: 0644
  notify: php72
  tags: php

- name: Install php 7.3
  homebrew:
    name: php@7.3
    state: present
  tags: php
- name: Install php73 ini configuration
  template:
    src: templates/php/99-local.ini.j2
    dest: /usr/local/etc/php/7.3/conf.d/99-local.ini
    mode: 0644
  tags: php
- name: Install php73 fpm configuration
  vars:
    - php_fpm_port: 9073
  template:
    src: templates/php/www.local.conf.j2
    dest: /usr/local/etc/php/7.3/php-fpm.d/www.local.conf
    mode: 0644
  tags: php

- name: Link php 7.2 as default php
  shell: "brew link --overwrite php@7.2 --force"
  register: brew_link_result
  changed_when: "'symlinks created' in brew_link_result.stdout"

- name: Create php bin symlinks
  shell: "ln -fs $(find /usr/local/Cellar/php* -name 'php' -type f | grep {{ item.version }} | head -n 1) /usr/local/bin/{{ item.alias }}"
  changed_when: false
  with_items:
    - { version: 7.1, alias: php71 }
    - { version: 7.2, alias: php72 }
    - { version: 7.3, alias: php73 }

- name: Install composer
  homebrew:
    name: composer
    state: present
  tags: php
